import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nav } from "../components/Nav";
import "./globals.css";

const interSans = Inter({ variable: "--font-inter-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerFooterHeight = 75;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.className} antialiased bg-gradient-to-r from-white via-blue-200 to-white  flex flex-col gap-10`}
      >
        <header className={`h-[${headerFooterHeight}px]`}>
          <Nav />
        </header>
        <div
          className={`flex flex-col h-[calc(100%-${
            headerFooterHeight * 2
          }px)] items-center gap-10`}
        >
          {children}
        </div>
        <footer className={`h-[${headerFooterHeight}px]`}>Footer</footer>
      </body>
    </html>
  );
}
