import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

import "./globals.css";

const interSans = Inter({ variable: "--font-inter-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.className} antialiased bg-gradient-to-r from-white via-blue-200 to-white  flex flex-col gap-10 justify-between`}
      >
        <ReactQueryProvider>
          <Header />
          <div className="flex flex-col h-[100%] items-baseline gap-10 w-[70%] mx-auto">
            {children}
          </div>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
